
red: context [#include %$ROOT-PATH$runtime/definitions.reds #include %$ROOT-PATH$runtime/macros.reds #include %$ROOT-PATH$runtime/structures.reds
cell!: alias struct! [
    header [integer!]
    data1 [integer!]
    data2 [integer!]
    data3 [integer!]
]
series-buffer!: alias struct! [
    flags [integer!]
    node [node-handle!]
    size [integer!]
    offset [cell!]
    tail [cell!]
]
root-base: as cell! 0
get-root: func [
    idx [integer!]
    return: [red-block!]
] [
    as red-block! root-base + idx
]
get-root-node: func [
    idx [integer!]
    return: [node-handle!]
    /local
    obj [red-object!]
] [
    obj: as red-object! get-root idx
    obj/ctx
]
#import ["libRedRT.dylib" stdcall [
    boot: "red/boot" [[red-internal]]
    get-build-date: "red/get-build-date" [[red-internal] return: [c-string!]]
    copy-cell: "red/copy-cell" [[red-internal] src [cell!] dst [cell!] return: [cell!]]
    get-root-node2: "red/get-root-node2" [[red-internal] idx [integer!] return: [integer!]]
    type-check-alt: "red/type-check-alt" [[red-internal] ref [cell!] expected [red-typeset!] index [integer!] arg [cell!] return: [cell!]]
    type-check: "red/type-check" [[red-internal] expected [red-typeset!] index [integer!] arg [cell!] return: [cell!]]
    eval-path*: "red/eval-path*" [[variadic red-internal] count [integer!] list [pointer! [uint64!]]]
    select-key*: "red/select-key*" [[red-internal] sub? [logic!] fetch? [logic!] return: [cell!]]
    alloc-bytes: "red/alloc-bytes" [[red-internal] size [integer!] return: [ptr-ptr!]]
    alloc-cells: "red/alloc-cells" [[red-internal] size [integer!] return: [ptr-ptr!]]
    resolve-node: "red/resolve-node" [[red-internal] handle [integer!] return: [ptr-ptr!]]
    resolve-series: "red/resolve-series" [[red-internal] handle [integer!] return: [series-buffer!]]
    node-handle-of: "red/node-handle-of" [[red-internal] node [ptr-ptr!] return: [integer!]]
    get-cmdline-args: "red/get-cmdline-args" [[red-internal] return: [cell!]]
    set-opt-refinement*: "red/set-opt-refinement*" [[red-internal] value [cell!] idx [integer!] nb [integer!]]
    set-top*: "red/set-top*" [[red-internal] word [red-word!] return: [cell!]]
    set-top-in*: "red/set-top-in*" [[red-internal] node [integer!] index [integer!] return: [cell!]]
    set-top-flush*: "red/set-top-flush*" [[red-internal] word [red-word!]]
    set-top-in-flush*: "red/set-top-in-flush*" [[red-internal] node [integer!] index [integer!]]
    set-in-ctx-flush*: "red/set-in-ctx-flush*" [[red-internal] node [integer!] index [integer!]]
    get-ptr*: "red/get-ptr*" [[red-internal] word [red-word!] return: [cell!]]
    get-local-ptr*: "red/get-local-ptr*" [[red-internal] node [integer!] index [integer!] return: [cell!]]
    call-with-array*: "red/call-with-array*" [[variadic red-internal] count [integer!] list [pointer! [uint64!]] return: [integer!]]
    get-libRedRT-bitarray: "red/get-libRedRT-bitarray" [[red-internal] return: [pointer! [integer!]]]
    fire: "red/fire" [[variadic red-internal] count [integer!] list [pointer! [uint64!]]]
    set-type: "red/set-type" [[red-internal] cell [cell!] type [integer!]]
    report: "red/report" [[red-internal] type [cell!] id [cell!] arg1 [cell!] arg2 [cell!] arg3 [cell!]]
    f_routine: "f_routine" [[red-internal]]
    f_also: "f_also" [[red-internal]]
    f_attempt: "f_attempt" [[red-internal]]
    f_comment: "f_comment" [[red-internal]]
    f_quit: "f_quit" [[red-internal]]
    f_empty?: "f_empty?" [[red-internal]]
    f_??: "f_??" [[red-internal]]
    f_probe: "f_probe" [[red-internal]]
    f_quote: "f_quote" [[red-internal]]
    f_first: "f_first" [[red-internal]]
    f_second: "f_second" [[red-internal]]
    f_third: "f_third" [[red-internal]]
    f_fourth: "f_fourth" [[red-internal]]
    f_fifth: "f_fifth" [[red-internal]]
    f_last: "f_last" [[red-internal]]
    f_spec-of: "f_spec-of" [[red-internal]]
    f_body-of: "f_body-of" [[red-internal]]
    f_words-of: "f_words-of" [[red-internal]]
    f_class-of: "f_class-of" [[red-internal]]
    f_values-of: "f_values-of" [[red-internal]]
    f_bitset?: "f_bitset?" [[red-internal]]
    f_binary?: "f_binary?" [[red-internal]]
    f_block?: "f_block?" [[red-internal]]
    f_char?: "f_char?" [[red-internal]]
    f_email?: "f_email?" [[red-internal]]
    f_file?: "f_file?" [[red-internal]]
    f_float?: "f_float?" [[red-internal]]
    f_get-path?: "f_get-path?" [[red-internal]]
    f_get-word?: "f_get-word?" [[red-internal]]
    f_hash?: "f_hash?" [[red-internal]]
    f_integer?: "f_integer?" [[red-internal]]
    f_issue?: "f_issue?" [[red-internal]]
    f_lit-path?: "f_lit-path?" [[red-internal]]
    f_lit-word?: "f_lit-word?" [[red-internal]]
    f_logic?: "f_logic?" [[red-internal]]
    f_map?: "f_map?" [[red-internal]]
    f_none?: "f_none?" [[red-internal]]
    f_pair?: "f_pair?" [[red-internal]]
    f_paren?: "f_paren?" [[red-internal]]
    f_path?: "f_path?" [[red-internal]]
    f_percent?: "f_percent?" [[red-internal]]
    f_refinement?: "f_refinement?" [[red-internal]]
    f_set-path?: "f_set-path?" [[red-internal]]
    f_set-word?: "f_set-word?" [[red-internal]]
    f_string?: "f_string?" [[red-internal]]
    f_tag?: "f_tag?" [[red-internal]]
    f_time?: "f_time?" [[red-internal]]
    f_typeset?: "f_typeset?" [[red-internal]]
    f_tuple?: "f_tuple?" [[red-internal]]
    f_unset?: "f_unset?" [[red-internal]]
    f_url?: "f_url?" [[red-internal]]
    f_word?: "f_word?" [[red-internal]]
    f_image?: "f_image?" [[red-internal]]
    f_date?: "f_date?" [[red-internal]]
    f_money?: "f_money?" [[red-internal]]
    f_ref?: "f_ref?" [[red-internal]]
    f_point2D?: "f_point2D?" [[red-internal]]
    f_point3D?: "f_point3D?" [[red-internal]]
    f_handle?: "f_handle?" [[red-internal]]
    f_error?: "f_error?" [[red-internal]]
    f_action?: "f_action?" [[red-internal]]
    f_native?: "f_native?" [[red-internal]]
    f_datatype?: "f_datatype?" [[red-internal]]
    f_function?: "f_function?" [[red-internal]]
    f_object?: "f_object?" [[red-internal]]
    f_op?: "f_op?" [[red-internal]]
    f_routine?: "f_routine?" [[red-internal]]
    f_vector?: "f_vector?" [[red-internal]]
    f_any-list?: "f_any-list?" [[red-internal]]
    f_any-block?: "f_any-block?" [[red-internal]]
    f_any-function?: "f_any-function?" [[red-internal]]
    f_any-object?: "f_any-object?" [[red-internal]]
    f_any-path?: "f_any-path?" [[red-internal]]
    f_any-string?: "f_any-string?" [[red-internal]]
    f_any-word?: "f_any-word?" [[red-internal]]
    f_series?: "f_series?" [[red-internal]]
    f_number?: "f_number?" [[red-internal]]
    f_immediate?: "f_immediate?" [[red-internal]]
    f_scalar?: "f_scalar?" [[red-internal]]
    f_all-word?: "f_all-word?" [[red-internal]]
    f_any-point?: "f_any-point?" [[red-internal]]
    f_planar?: "f_planar?" [[red-internal]]
    f_to-bitset: "f_to-bitset" [[red-internal]]
    f_to-binary: "f_to-binary" [[red-internal]]
    f_to-block: "f_to-block" [[red-internal]]
    f_to-char: "f_to-char" [[red-internal]]
    f_to-email: "f_to-email" [[red-internal]]
    f_to-file: "f_to-file" [[red-internal]]
    f_to-float: "f_to-float" [[red-internal]]
    f_to-get-path: "f_to-get-path" [[red-internal]]
    f_to-get-word: "f_to-get-word" [[red-internal]]
    f_to-hash: "f_to-hash" [[red-internal]]
    f_to-integer: "f_to-integer" [[red-internal]]
    f_to-issue: "f_to-issue" [[red-internal]]
    f_to-lit-path: "f_to-lit-path" [[red-internal]]
    f_to-lit-word: "f_to-lit-word" [[red-internal]]
    f_to-logic: "f_to-logic" [[red-internal]]
    f_to-map: "f_to-map" [[red-internal]]
    f_to-none: "f_to-none" [[red-internal]]
    f_to-pair: "f_to-pair" [[red-internal]]
    f_to-paren: "f_to-paren" [[red-internal]]
    f_to-path: "f_to-path" [[red-internal]]
    f_to-percent: "f_to-percent" [[red-internal]]
    f_to-refinement: "f_to-refinement" [[red-internal]]
    f_to-set-path: "f_to-set-path" [[red-internal]]
    f_to-set-word: "f_to-set-word" [[red-internal]]
    f_to-string: "f_to-string" [[red-internal]]
    f_to-tag: "f_to-tag" [[red-internal]]
    f_to-time: "f_to-time" [[red-internal]]
    f_to-typeset: "f_to-typeset" [[red-internal]]
    f_to-tuple: "f_to-tuple" [[red-internal]]
    f_to-unset: "f_to-unset" [[red-internal]]
    f_to-url: "f_to-url" [[red-internal]]
    f_to-word: "f_to-word" [[red-internal]]
    f_to-image: "f_to-image" [[red-internal]]
    f_to-date: "f_to-date" [[red-internal]]
    f_to-money: "f_to-money" [[red-internal]]
    f_to-ref: "f_to-ref" [[red-internal]]
    f_to-point2D: "f_to-point2D" [[red-internal]]
    f_to-point3D: "f_to-point3D" [[red-internal]]
    f_context: "f_context" [[red-internal]]
    f_alter: "f_alter" [[red-internal]]
    f_offset?: "f_offset?" [[red-internal]]
    f_repend: "f_repend" [[red-internal]]
    f_replace: "f_replace" [[red-internal]]
    f_math: "f_math" [[red-internal]]
    f_charset: "f_charset" [[red-internal]]
    f_ctx||183~on-parse-event: "f_ctx||183~on-parse-event" [[red-internal] octx [integer!]]
    f_parse-trace: "f_parse-trace" [[red-internal] octx [integer!]]
    f_suffix?: "f_suffix?" [[red-internal]]
    f_scan: "f_scan" [[red-internal]]
    f_load: "f_load" [[red-internal]]
    f_save: "f_save" [[red-internal]]
    f_cause-error: "f_cause-error" [[red-internal]]
    f_pad: "f_pad" [[red-internal]]
    f_mod: "f_mod" [[red-internal]]
    f_modulo: "f_modulo" [[red-internal]]
    f_eval-set-path: "f_eval-set-path" [[red-internal]]
    f_to-red-file: "f_to-red-file" [[red-internal]]
    f_dir?: "f_dir?" [[red-internal]]
    f_normalize-dir: "f_normalize-dir" [[red-internal]]
    f_what-dir: "f_what-dir" [[red-internal]]
    f_change-dir: "f_change-dir" [[red-internal]]
    f_make-dir: "f_make-dir" [[red-internal]]
    f_extract: "f_extract" [[red-internal]]
    f_extract-boot-args: "f_extract-boot-args" [[red-internal]]
    f_collect: "f_collect" [[red-internal]]
    f_flip-exe-flag: "f_flip-exe-flag" [[red-internal]]
    f_split: "f_split" [[red-internal]]
    f_dirize: "f_dirize" [[red-internal]]
    f_clean-path: "f_clean-path" [[red-internal]]
    f_split-path: "f_split-path" [[red-internal]]
    f_do-file: "f_do-file" [[red-internal]]
    f_path-thru: "f_path-thru" [[red-internal]]
    f_exists-thru?: "f_exists-thru?" [[red-internal]]
    f_read-thru: "f_read-thru" [[red-internal]]
    f_load-thru: "f_load-thru" [[red-internal]]
    f_do-thru: "f_do-thru" [[red-internal]]
    f_cos: "f_cos" [[red-internal]]
    f_sin: "f_sin" [[red-internal]]
    f_tan: "f_tan" [[red-internal]]
    f_acos: "f_acos" [[red-internal]]
    f_asin: "f_asin" [[red-internal]]
    f_atan: "f_atan" [[red-internal]]
    f_atan2: "f_atan2" [[red-internal]]
    f_sqrt: "f_sqrt" [[red-internal]]
    f_to-UTC-date: "f_to-UTC-date" [[red-internal]]
    f_to-local-date: "f_to-local-date" [[red-internal]]
    f_show-memory-stats: "f_show-memory-stats" [[red-internal]]
    f_transcode-trace: "f_transcode-trace" [[red-internal]]
    f_rejoin: "f_rejoin" [[red-internal]]
    f_sum: "f_sum" [[red-internal]]
    f_average: "f_average" [[red-internal]]
    f_last?: "f_last?" [[red-internal]]
    f_dt: "f_dt" [[red-internal]]
    f_clock: "f_clock" [[red-internal]]
    f_ctx||264~interpreted?: "f_ctx||264~interpreted?" [[red-internal] octx [integer!]]
    f_ctx||267~on-change*: "f_ctx||267~on-change*" [[red-internal] octx [integer!]]
    f_ctx||276~on-change*: "f_ctx||276~on-change*" [[red-internal] octx [integer!]]
    f_ctx||276~on-deep-change*: "f_ctx||276~on-deep-change*" [[red-internal] octx [integer!]]
    f_ctx||282~on-change*: "f_ctx||282~on-change*" [[red-internal] octx [integer!]]
    f_ctx||280~on-change*: "f_ctx||280~on-change*" [[red-internal] octx [integer!]]
    f_ctx||280~on-deep-change*: "f_ctx||280~on-deep-change*" [[red-internal] octx [integer!]]
    f_ctx||312~trapper: "f_ctx||312~trapper" [[red-internal] octx [integer!]]
    f_ctx||312~tracer: "f_ctx||312~tracer" [[red-internal] octx [integer!]]
    f_ctx||328~encode: "f_ctx||328~encode" [[red-internal] octx [integer!]]
    f_ctx||332~on-change*: "f_ctx||332~on-change*" [[red-internal] octx [integer!]]
    f_ctx||335~on-change*: "f_ctx||335~on-change*" [[red-internal] octx [integer!]]
    f_ctx||335~on-deep-change*: "f_ctx||335~on-deep-change*" [[red-internal] octx [integer!]]
    f_reactor: "f_reactor" [[red-internal]]
    f_deep-reactor: "f_deep-reactor" [[red-internal]]
    f_ctx||341~add-relation: "f_ctx||341~add-relation" [[red-internal] octx [integer!]]
    f_ctx||341~identify-sources: "f_ctx||341~identify-sources" [[red-internal] octx [integer!]]
    f_ctx||341~eval: "f_ctx||341~eval" [[red-internal] octx [integer!]]
    f_ctx||341~eval-reaction: "f_ctx||341~eval-reaction" [[red-internal] octx [integer!]]
    f_ctx||341~pending?: "f_ctx||341~pending?" [[red-internal] octx [integer!]]
    f_ctx||341~check: "f_ctx||341~check" [[red-internal] octx [integer!]]
    f_no-react: "f_no-react" [[red-internal] octx [integer!]]
    f_stop-reactor: "f_stop-reactor" [[red-internal] octx [integer!]]
    f_clear-reactions: "f_clear-reactions" [[red-internal] octx [integer!]]
    f_dump-reactions: "f_dump-reactions" [[red-internal] octx [integer!]]
    f_relate: "f_relate" [[red-internal] octx [integer!]]
    f_is: "f_is" [[red-internal] octx [integer!]]
    f_react?: "f_react?" [[red-internal] octx [integer!]]
    f_react: "f_react" [[red-internal] octx [integer!]]
    f_register-scheme: "f_register-scheme" [[red-internal]]
    f_ctx||358~alpha-num+: "f_ctx||358~alpha-num+" [[red-internal] octx [integer!]]
    f_ctx||358~parse-url: "f_ctx||358~parse-url" [[red-internal] octx [integer!]]
    f_decode-url: "f_decode-url" [[red-internal] octx [integer!]]
    f_encode-url: "f_encode-url" [[red-internal] octx [integer!]]
    f_ctx||364~do-quit: "f_ctx||364~do-quit" [[red-internal] octx [integer!]]
    f_ctx||364~throw-error: "f_ctx||364~throw-error" [[red-internal] octx [integer!]]
    f_ctx||364~syntax-error: "f_ctx||364~syntax-error" [[red-internal] octx [integer!]]
    f_ctx||364~do-safe: "f_ctx||364~do-safe" [[red-internal] octx [integer!]]
    f_ctx||364~do-code: "f_ctx||364~do-code" [[red-internal] octx [integer!]]
    f_ctx||364~rebind-all: "f_ctx||364~rebind-all" [[red-internal] octx [integer!]]
    f_ctx||364~count-args: "f_ctx||364~count-args" [[red-internal] octx [integer!]]
    f_ctx||364~arg-mode?: "f_ctx||364~arg-mode?" [[red-internal] octx [integer!]]
    f_ctx||364~func-arity?: "f_ctx||364~func-arity?" [[red-internal] octx [integer!]]
    f_ctx||364~value-path?: "f_ctx||364~value-path?" [[red-internal] octx [integer!]]
    f_ctx||364~fetch-next: "f_ctx||364~fetch-next" [[red-internal] octx [integer!]]
    f_ctx||364~eval: "f_ctx||364~eval" [[red-internal] octx [integer!]]
    f_ctx||364~do-macro: "f_ctx||364~do-macro" [[red-internal] octx [integer!]]
    f_ctx||364~register-macro: "f_ctx||364~register-macro" [[red-internal] octx [integer!]]
    f_ctx||364~reset: "f_ctx||364~reset" [[red-internal] octx [integer!]]
    f_ctx||364~expand: "f_ctx||364~expand" [[red-internal] octx [integer!]]
    f_expand-directives: "f_expand-directives" [[red-internal] octx [integer!]]
    f_ctx||383~calc-max: "f_ctx||383~calc-max" [[red-internal] octx [integer!]]
    f_ctx||383~show-context: "f_ctx||383~show-context" [[red-internal] octx [integer!]]
    f_ctx||383~show-parents: "f_ctx||383~show-parents" [[red-internal] octx [integer!]]
    f_ctx||383~show-stack: "f_ctx||383~show-stack" [[red-internal] octx [integer!]]
    f_ctx||383~show-watching: "f_ctx||383~show-watching" [[red-internal] octx [integer!]]
    f_ctx||383~do-command: "f_ctx||383~do-command" [[red-internal] octx [integer!]]
    f_ctx||383~debugger: "f_ctx||383~debugger" [[red-internal] octx [integer!]]
    f_ctx||400~mold-part: "f_ctx||400~mold-part" [[red-internal] octx [integer!]]
    f_ctx||400~dumper: "f_ctx||400~dumper" [[red-internal] octx [integer!]]
    f_ctx||400~push: "f_ctx||400~push" [[red-internal] octx [integer!]]
    f_ctx||400~drop: "f_ctx||400~drop" [[red-internal] octx [integer!]]
    f_ctx||400~pop: "f_ctx||400~pop" [[red-internal] octx [integer!]]
    f_ctx||400~top-of: "f_ctx||400~top-of" [[red-internal] octx [integer!]]
    f_ctx||400~step: "f_ctx||400~step" [[red-internal] octx [integer!]]
    f_ctx||409~put: "f_ctx||409~put" [[red-internal] octx [integer!]]
    f_ctx||409~get: "f_ctx||409~get" [[red-internal] octx [integer!]]
    f_ctx||413~save-level: "f_ctx||413~save-level" [[red-internal] octx [integer!]]
    f_ctx||413~unroll-level: "f_ctx||413~unroll-level" [[red-internal] octx [integer!]]
    f_ctx||413~reset: "f_ctx||413~reset" [[red-internal] octx [integer!]]
    f_ctx||413~collector: "f_ctx||413~collector" [[red-internal] octx [integer!]]
    f_ctx||400~guided-trace: "f_ctx||400~guided-trace" [[red-internal] octx [integer!]]
    f_ctx||420~inspect: "f_ctx||420~inspect" [[red-internal] octx [integer!]]
    f_ctx||383~profiler: "f_ctx||383~profiler" [[red-internal] octx [integer!]]
    f_ctx||383~do-handler: "f_ctx||383~do-handler" [[red-internal] octx [integer!]]
    f_profile: "f_profile" [[red-internal] octx [integer!]]
    f_trace: "f_trace" [[red-internal] octx [integer!]]
    f_debug: "f_debug" [[red-internal] octx [integer!]]
    f_hex-to-rgb: "f_hex-to-rgb" [[red-internal]]
    f_within?: "f_within?" [[red-internal]]
    f_overlap?: "f_overlap?" [[red-internal]]
    f_distance?: "f_distance?" [[red-internal]]
    f_send-event: "f_send-event" [[red-internal]]
    f_face?: "f_face?" [[red-internal]]
    f_get-current-screen: "f_get-current-screen" [[red-internal]]
    f_size-text: "f_size-text" [[red-internal]]
    f_caret-to-offset: "f_caret-to-offset" [[red-internal]]
    f_offset-to-caret: "f_offset-to-caret" [[red-internal]]
    f_offset-to-char: "f_offset-to-char" [[red-internal]]
    f_ctx||441~tail-idx?: "f_ctx||441~tail-idx?" [[red-internal] octx [integer!]]
    f_ctx||441~push-color: "f_ctx||441~push-color" [[red-internal] octx [integer!]]
    f_ctx||441~pop-color: "f_ctx||441~pop-color" [[red-internal] octx [integer!]]
    f_ctx||441~close-colors: "f_ctx||441~close-colors" [[red-internal] octx [integer!]]
    f_ctx||441~push: "f_ctx||441~push" [[red-internal] octx [integer!]]
    f_ctx||441~pop: "f_ctx||441~pop" [[red-internal] octx [integer!]]
    f_ctx||441~pop-all: "f_ctx||441~pop-all" [[red-internal] octx [integer!]]
    f_ctx||441~optimize: "f_ctx||441~optimize" [[red-internal] octx [integer!]]
    f_rtd-layout: "f_rtd-layout" [[red-internal] octx [integer!]]
    f_ctx||439~line-height?: "f_ctx||439~line-height?" [[red-internal] octx [integer!]]
    f_ctx||439~line-count?: "f_ctx||439~line-count?" [[red-internal] octx [integer!]]
    f_metrics?: "f_metrics?" [[red-internal]]
    f_set-flag: "f_set-flag" [[red-internal]]
    f_debug-info?: "f_debug-info?" [[red-internal]]
    f_on-face-deep-change*: "f_on-face-deep-change*" [[red-internal]]
    f_link-tabs-to-parent: "f_link-tabs-to-parent" [[red-internal]]
    f_link-sub-to-parent: "f_link-sub-to-parent" [[red-internal]]
    f_update-font-faces: "f_update-font-faces" [[red-internal]]
    f_ctx||461~on-change*: "f_ctx||461~on-change*" [[red-internal] octx [integer!]]
    f_ctx||461~on-deep-change*: "f_ctx||461~on-deep-change*" [[red-internal] octx [integer!]]
    f_ctx||465~on-change*: "f_ctx||465~on-change*" [[red-internal] octx [integer!]]
    f_ctx||465~on-deep-change*: "f_ctx||465~on-deep-change*" [[red-internal] octx [integer!]]
    f_ctx||469~on-change*: "f_ctx||469~on-change*" [[red-internal] octx [integer!]]
    f_ctx||472~on-change*: "f_ctx||472~on-change*" [[red-internal] octx [integer!]]
    f_ctx||475~capture-events: "f_ctx||475~capture-events" [[red-internal] octx [integer!]]
    f_ctx||475~awake: "f_ctx||475~awake" [[red-internal] octx [integer!]]
    f_ctx||475~on-change*: "f_ctx||475~on-change*" [[red-internal] octx [integer!]]
    f_ctx||484~all-windows-closed?: "f_ctx||484~all-windows-closed?" [[red-internal] octx [integer!]]
    f_ctx||484~refresh-screens: "f_ctx||484~refresh-screens" [[red-internal] octx [integer!]]
    f_ctx||484~init: "f_ctx||484~init" [[red-internal] octx [integer!]]
    f_draw: "f_draw" [[red-internal]]
    f_ctx||494~title-ize: "f_ctx||494~title-ize" [[red-internal] octx [integer!]]
    f_ctx||494~sentence-ize: "f_ctx||494~sentence-ize" [[red-internal] octx [integer!]]
    f_ctx||494~capitalize: "f_ctx||494~capitalize" [[red-internal] octx [integer!]]
    f_ctx||494~adjust-buttons: "f_ctx||494~adjust-buttons" [[red-internal] octx [integer!]]
    f_ctx||494~Cancel-OK: "f_ctx||494~Cancel-OK" [[red-internal] octx [integer!]]
    f_ctx||492~process: "f_ctx||492~process" [[red-internal] octx [integer!]]
    f_ctx||490~throw-error: "f_ctx||490~throw-error" [[red-internal] octx [integer!]]
    f_ctx||490~process-reactors: "f_ctx||490~process-reactors" [[red-internal] octx [integer!]]
    f_ctx||490~opt-as-integer: "f_ctx||490~opt-as-integer" [[red-internal] octx [integer!]]
    f_ctx||490~calc-size: "f_ctx||490~calc-size" [[red-internal] octx [integer!]]
    f_ctx||490~align-faces: "f_ctx||490~align-faces" [[red-internal] octx [integer!]]
    f_ctx||490~resize-child-panels: "f_ctx||490~resize-child-panels" [[red-internal] octx [integer!]]
    f_ctx||490~clean-style: "f_ctx||490~clean-style" [[red-internal] octx [integer!]]
    f_ctx||490~process-draw: "f_ctx||490~process-draw" [[red-internal] octx [integer!]]
    f_ctx||490~pre-load: "f_ctx||490~pre-load" [[red-internal] octx [integer!]]
    f_ctx||490~preset-focus: "f_ctx||490~preset-focus" [[red-internal] octx [integer!]]
    f_ctx||490~add-option: "f_ctx||490~add-option" [[red-internal] octx [integer!]]
    f_ctx||490~add-flag: "f_ctx||490~add-flag" [[red-internal] octx [integer!]]
    f_ctx||490~add-bounds: "f_ctx||490~add-bounds" [[red-internal] octx [integer!]]
    f_ctx||490~fetch-value: "f_ctx||490~fetch-value" [[red-internal] octx [integer!]]
    f_ctx||490~fetch-argument: "f_ctx||490~fetch-argument" [[red-internal] octx [integer!]]
    f_ctx||490~fetch-expr: "f_ctx||490~fetch-expr" [[red-internal] octx [integer!]]
    f_ctx||490~fetch-options: "f_ctx||490~fetch-options" [[red-internal] octx [integer!]]
    f_ctx||490~make-actor: "f_ctx||490~make-actor" [[red-internal] octx [integer!]]
    f_layout: "f_layout" [[red-internal] octx [integer!]]
    f_do-events: "f_do-events" [[red-internal]]
    f_stop-events: "f_stop-events" [[red-internal]]
    f_do-safe: "f_do-safe" [[red-internal]]
    f_do-actor: "f_do-actor" [[red-internal]]
    f_show: "f_show" [[red-internal]]
    f_unview: "f_unview" [[red-internal]]
    f_view: "f_view" [[red-internal]]
    f_center-face: "f_center-face" [[red-internal]]
    f_make-face: "f_make-face" [[red-internal]]
    f_dump-face: "f_dump-face" [[red-internal]]
    f_do-no-sync: "f_do-no-sync" [[red-internal]]
    f_get-scroller: "f_get-scroller" [[red-internal]]
    f_get-face-pane: "f_get-face-pane" [[red-internal]]
    f_get-focusable: "f_get-focusable" [[red-internal]]
    f_insert-event-func: "f_insert-event-func" [[red-internal]]
    f_remove-event-func: "f_remove-event-func" [[red-internal]]
    f_request-font: "f_request-font" [[red-internal]]
    f_request-file: "f_request-file" [[red-internal]]
    f_request-dir: "f_request-dir" [[red-internal]]
    f_set-focus: "f_set-focus" [[red-internal]]
    f_foreach-face: "f_foreach-face" [[red-internal]]
    f_alert: "f_alert" [[red-internal]]
    f_~anon545~: "f_~anon545~" [[red-internal]]
    f_~anon547~: "f_~anon547~" [[red-internal]]
    f_ctx||549~encode: "f_ctx||549~encode" [[red-internal] octx [integer!]]
    f_ctx||549~decode: "f_ctx||549~decode" [[red-internal] octx [integer!]]
    f_ctx||556~to-csv-line: "f_ctx||556~to-csv-line" [[red-internal] octx [integer!]]
    f_ctx||556~escape-value: "f_ctx||556~escape-value" [[red-internal] octx [integer!]]
    f_ctx||556~next-column-name: "f_ctx||556~next-column-name" [[red-internal] octx [integer!]]
    f_ctx||556~make-header: "f_ctx||556~make-header" [[red-internal] octx [integer!]]
    f_ctx||556~get-columns: "f_ctx||556~get-columns" [[red-internal] octx [integer!]]
    f_ctx||556~encode-map: "f_ctx||556~encode-map" [[red-internal] octx [integer!]]
    f_ctx||556~encode-maps: "f_ctx||556~encode-maps" [[red-internal] octx [integer!]]
    f_ctx||556~encode-flat: "f_ctx||556~encode-flat" [[red-internal] octx [integer!]]
    f_ctx||556~encode-blocks: "f_ctx||556~encode-blocks" [[red-internal] octx [integer!]]
    f_load-csv: "f_load-csv" [[red-internal] octx [integer!]]
    f_to-csv: "f_to-csv" [[red-internal] octx [integer!]]
    f_ctx||569~push: "f_ctx||569~push" [[red-internal] octx [integer!]]
    f_ctx||569~pop: "f_ctx||569~pop" [[red-internal] octx [integer!]]
    f_ctx||569~emit: "f_ctx||569~emit" [[red-internal] octx [integer!]]
    f_load-json: "f_load-json" [[red-internal] octx [integer!]]
    f_ctx||575~init-state: "f_ctx||575~init-state" [[red-internal] octx [integer!]]
    f_ctx||575~emit-indent: "f_ctx||575~emit-indent" [[red-internal] octx [integer!]]
    f_ctx||575~emit-key-value: "f_ctx||575~emit-key-value" [[red-internal] octx [integer!]]
    f_ctx||575~red-to-json-value: "f_ctx||575~red-to-json-value" [[red-internal] octx [integer!]]
    f_to-json: "f_to-json" [[red-internal] octx [integer!]]
    f_ctx||582~encode: "f_ctx||582~encode" [[red-internal] octx [integer!]]
    f_ctx||582~decode: "f_ctx||582~decode" [[red-internal] octx [integer!]]
    f_keep: "f_keep" [[red-internal]]
    quit-return: "quit-return" [[red-internal] status [integer!]]
    set-quiet: "set-quiet" [[red-internal] word [cell!] value [cell!] return: [cell!]]
    set-slot-quiet: "set-slot-quiet" [[red-internal] series [cell!] value [cell!]]
    shift-right: "shift-right" [[red-internal] data [integer!] bits [integer!]]
    shift-left: "shift-left" [[red-internal] data [integer!] bits [integer!]]
    shift-logical: "shift-logical" [[red-internal] data [integer!] bits [integer!]]
    last-lf?: "last-lf?" [[red-internal]]
    get-current-dir: "get-current-dir" [[red-internal]]
    set-current-dir: "set-current-dir" [[red-internal] path [red-file!]]
    create-dir: "create-dir" [[red-internal] path [red-file!]]
    exists?: "exists?" [[red-internal] path [red-file!] return: [logic!]]
    os-info: "os-info" [[red-internal]]
    as-color: "as-color" [[red-internal] r [integer!] g [integer!] b [integer!]]
    as-ipv4: "as-ipv4" [[red-internal] a [integer!] b [integer!] c [integer!] d [integer!]]
    as-rgba: "as-rgba" [[red-internal] r [integer!] g [integer!] b [integer!] a [integer!]]
    count-chars: "count-chars" [[red-internal] start [red-binary!] pos [red-binary!] return: [integer!]]
    stack-size?: "stack-size?" [[red-internal] return: [integer!]]
    pick-stack: "pick-stack" [[red-internal] idx [integer!]]
    frame-index?: "frame-index?" [[red-internal] return: [integer!]]
    collect-calls: "collect-calls" [[red-internal] blk [red-block!]]
    tracing?: "tracing?" [[red-internal]]
    read-clipboard: "read-clipboard" [[red-internal] return: [cell!]]
    write-clipboard: "write-clipboard" [[red-internal] data [cell!] return: [logic!]]
    write-stdout: "write-stdout" [[red-internal] data [cell!]]
    __make-sys-object: "__make-sys-object" [[red-internal]]
    ctx||270~active?: "ctx||270~active?" [[red-internal] return: [logic!]]
    ctx||270~series-cycles: "ctx||270~series-cycles" [[red-internal] return: [integer!]]
    ctx||270~nodes-cycles: "ctx||270~nodes-cycles" [[red-internal] return: [integer!]]
    ctx||270~pinned-frames: "ctx||270~pinned-frames" [[red-internal] return: [integer!]]
    ctx||270~pinned-bytes: "ctx||270~pinned-bytes" [[red-internal] return: [integer!]]
    ctx||316~encode: "ctx||316~encode" [[red-internal] img [red-image!] where [cell!]]
    ctx||316~decode: "ctx||316~decode" [[red-internal] data [cell!]]
    ctx||319~encode: "ctx||319~encode" [[red-internal] img [red-image!] where [cell!]]
    ctx||319~decode: "ctx||319~decode" [[red-internal] data [cell!]]
    ctx||322~encode: "ctx||322~encode" [[red-internal] img [red-image!] where [cell!]]
    ctx||322~decode: "ctx||322~decode" [[red-internal] data [cell!]]
    ctx||325~encode: "ctx||325~encode" [[red-internal] img [red-image!] where [cell!]]
    ctx||325~decode: "ctx||325~decode" [[red-internal] data [cell!]]
    ctx||328~encode*: "ctx||328~encode*" [[red-internal] data [cell!] compact? [logic!]]
    ctx||328~decode: "ctx||328~decode" [[red-internal] payload [cell!]]
    event?: "event?" [[red-internal] value [cell!] return: [logic!]]
    send-event-os: "send-event-os" [[red-internal] event [red-event!] queued? [logic!] return: [logic!]]
    find-flag?: "find-flag?" [[red-internal] facet [cell!] flag [red-word!]]
    ctx||484~make-null-handle: "ctx||484~make-null-handle" [[red-internal]]
    ctx||484~fetch-all-screens: "ctx||484~fetch-all-screens" [[red-internal]]
    ctx||484~get-current-screen: "ctx||484~get-current-screen" [[red-internal]]
    ctx||484~get-screen-size: "ctx||484~get-screen-size" [[red-internal] id [integer!]]
    ctx||484~size-text: "ctx||484~size-text" [[red-internal] face [red-object!] value [cell!]]
    ctx||484~on-change-facet: "ctx||484~on-change-facet" [[red-internal] owner [red-object!] word [red-word!] value [cell!] action [red-word!] new [cell!] index [integer!] part [integer!]]
    ctx||484~update-text: "ctx||484~update-text" [[red-internal] face [red-object!]]
    ctx||484~update-font: "ctx||484~update-font" [[red-internal] font [red-object!] flags [integer!]]
    ctx||484~update-para: "ctx||484~update-para" [[red-internal] face [red-object!] flags [integer!]]
    ctx||484~destroy-view: "ctx||484~destroy-view" [[red-internal] face [red-object!] empty? [logic!]]
    ctx||484~detach-image: "ctx||484~detach-image" [[red-internal] img [red-image!]]
    ctx||484~update-view: "ctx||484~update-view" [[red-internal] face [red-object!]]
    ctx||484~refresh-window: "ctx||484~refresh-window" [[red-internal] h [red-handle!]]
    ctx||484~redraw: "ctx||484~redraw" [[red-internal] face [red-object!]]
    ctx||484~show-window: "ctx||484~show-window" [[red-internal] id [red-handle!]]
    ctx||484~make-view: "ctx||484~make-view" [[red-internal] face [red-object!] parent [red-handle!]]
    ctx||484~draw-image: "ctx||484~draw-image" [[red-internal] image [red-image!] cmds [red-block!]]
    ctx||484~draw-face: "ctx||484~draw-face" [[red-internal] face [red-object!] cmds [red-block!]]
    ctx||484~do-event-loop: "ctx||484~do-event-loop" [[red-internal] no-wait? [logic!]]
    ctx||484~exit-event-loop: "ctx||484~exit-event-loop" [[red-internal]]
    ctx||484~request-font: "ctx||484~request-font" [[red-internal] font [red-object!] selected [cell!] mono? [logic!]]
    ctx||484~request-file: "ctx||484~request-file" [[red-internal] title [cell!] name [cell!] filter [cell!] save? [logic!] multi? [logic!]]
    ctx||484~request-dir: "ctx||484~request-dir" [[red-internal] title [cell!] dir [cell!] filter [cell!] keep? [logic!] multi? [logic!]]
    ctx||484~text-box-metrics: "ctx||484~text-box-metrics" [[red-internal] box [red-object!] arg0 [cell!] type [integer!]]
    ctx||484~update-scroller: "ctx||484~update-scroller" [[red-internal] scroller [red-object!] flags [integer!]]
    ctx||484~set-dark-mode: "ctx||484~set-dark-mode" [[red-internal] face [red-object!] dark? [logic!]]
    ctx||484~support-dark-mode?: "ctx||484~support-dark-mode?" [[red-internal] return: [logic!]]
    ctx||484~toggle-GPU: "ctx||484~toggle-GPU" [[red-internal]]
    throw-draw-error: "throw-draw-error" [[red-internal] cmds [red-block!] cmd [cell!] catch? [logic!]]
    _throw-draw-error: "_throw-draw-error" [[red-internal] cmds [red-block!] cmd [cell!] cat [cell!] id [cell!] catch? [logic!] cycle? [logic!]]
    transparent-color?: "transparent-color?" [[red-internal] color [red-tuple!] return: [logic!]]
    get-color-int: "get-color-int" [[red-internal] tp [red-tuple!] alpha? [pointer! [integer!]] return: [integer!]]
    get-float: "get-float" [[red-internal] int [red-integer!] return: [float!]]
    get-float32: "get-float32" [[red-internal] int [red-integer!] return: [float32!]]
    reverse-int-array: "reverse-int-array" [[red-internal] array [pointer! [integer!]] count [integer!]]
    reverse-float32-array: "reverse-float32-array" [[red-internal] array [pointer! [float32!]] count [integer!]]
    old-gradient-pen: "old-gradient-pen" [[red-internal] DC [draw-ctx!] cmds [red-block!] start [cell!] tail [cell!] cmd [cell!] sym [integer!] catch? [logic!] return: [cell!]]
    check-pen: "check-pen" [[red-internal] DC [draw-ctx!] cmds [red-block!] start [cell!] tail [cell!] cmd [cell!] sym [integer!] catch? [logic!] return: [cell!]]
    check-line: "check-line" [[red-internal] DC [draw-ctx!] cmds [red-block!] start [cell!] tail [cell!] cmd [cell!] sym [integer!] catch? [logic!] return: [cell!]]
    parse-shape: "parse-shape" [[red-internal] DC [draw-ctx!] cmds [red-block!] draw? [logic!] catch? [logic!] sub? [logic!]]
    parse-draw: "parse-draw" [[red-internal] DC [draw-ctx!] cmds [red-block!] catch? [logic!]]
    do-draw: "do-draw" [[red-internal] handle [pointer! [integer!]] img [red-image!] cmds [red-block!] on-graphic? [logic!] cache? [logic!] paint? [logic!] catch? [logic!]]
    parse-text-styles: "parse-text-styles" [[red-internal] dc [pointer! [integer!]] layout [pointer! [integer!]] cmds [red-block!] text [red-string!] catch? [logic!]]
    ctx||569~unescape: "ctx||569~unescape" [[red-internal] str [red-string!] return: [red-string!]]
    f_time-it: "f_dt" [[red-internal]]
    f_single?: "f_last?" [[red-internal]]
    f_keys-of: "f_words-of" [[red-internal]]
    f_object: "f_context" [[red-internal]]
    f_halt: "f_quit" [[red-internal]]
    f_ctx||400~emit: "red/natives/print*" [[red-internal] check? [logic!]]
    root: "red/root" [red-block!]
    stk-bottom: "red/stk-bottom" [int-ptr!]
    unset-value: "red/unset-value" [cell!]
    none-value: "red/none-value" [cell!]
    true-value: "red/true-value" [cell!]
    false-value: "red/false-value" [cell!]
    boot?: "red/boot?" [logic!]
]]
redbin: context [
    #import ["libRedRT.dylib" stdcall [
        boot-load: "red/redbin/boot-load" [[red-internal] payload [pointer! [byte!]] keep? [logic!] return: [cell!]]
    ]]
]
platform: context [
    #import ["libRedRT.dylib" stdcall [
        prin*: "red/platform/prin*" [[red-internal] s [c-string!] return: [c-string!]]
        prin-int*: "red/platform/prin-int*" [[red-internal] i [integer!] return: [integer!]]
        prin-hex*: "red/platform/prin-hex*" [[red-internal] i [integer!] return: [integer!]]
        prin-2hex*: "red/platform/prin-2hex*" [[red-internal] i [integer!] return: [integer!]]
        prin-float*: "red/platform/prin-float*" [[red-internal] f [float!] return: [float!]]
        prin-float32*: "red/platform/prin-float32*" [[red-internal] f [float32!] return: [float32!]]
    ]]
]
stack: context [
    #import ["libRedRT.dylib" stdcall [
        mark: "red/stack/mark" [[red-internal] fun [red-word!] type [integer!]]
        mark-native: "red/stack/mark-native" [[red-internal] fun [red-word!]]
        mark-func: "red/stack/mark-func" [[red-internal] fun [red-word!] ctx-name [integer!]]
        mark-loop: "red/stack/mark-loop" [[red-internal] fun [red-word!]]
        mark-try: "red/stack/mark-try" [[red-internal] fun [red-word!]]
        mark-try-all: "red/stack/mark-try-all" [[red-internal] fun [red-word!]]
        mark-catch: "red/stack/mark-catch" [[red-internal] fun [red-word!]]
        mark-func-body: "red/stack/mark-func-body" [[red-internal] fun [red-word!]]
        unwind: "red/stack/unwind" [[red-internal]]
        unwind-last: "red/stack/unwind-last" [[red-internal] return: [cell!]]
        unwind-flush: "red/stack/unwind-flush" [[red-internal]]
        reset: "red/stack/reset" [[red-internal] return: [cell!]]
        keep: "red/stack/keep" [[red-internal] return: [cell!]]
        push: "red/stack/push" [[red-internal] value [cell!] return: [cell!]]
        unroll: "red/stack/unroll" [[red-internal] flags [integer!]]
        unroll-to: "red/stack/unroll-to" [[red-internal] target [pointer! [integer!]] keep-result? [logic!]]
        unroll-loop: "red/stack/unroll-loop" [[red-internal] inner? [logic!]]
        revert: "red/stack/revert" [[red-internal]]
        adjust-post-try: "red/stack/adjust-post-try" [[red-internal]]
        pop: "red/stack/pop" [[red-internal] positions [integer!]]
        set-last: "red/stack/set-last" [[red-internal] last [cell!] return: [cell!]]
        store-values: "red/stack/store-values" [[red-internal] ptr [cell!] return: [integer!]]
        get-values: "red/stack/get-values" [[red-internal] offset [integer!] return: [cell!]]
        push*: "red/stack/push*" [[red-internal] return: [cell!]]
        arguments: "red/stack/arguments" [cell!]
        top: "red/stack/top" [cell!]
        bottom: "red/stack/bottom" [cell!]
        ctop: "red/stack/ctop" [int-ptr!]
    ]]
    #enum flags! [FRAME_FUNCTION: 16777216]
]
interpreter: context [
    #import ["libRedRT.dylib" stdcall [
        eval-path: "red/interpreter/eval-path" [[red-internal] value [cell!] pc [cell!] end [cell!] code [red-block!] set? [logic!] get? [logic!] sub? [logic!] case? [logic!] return: [cell!]]
    ]]
]
lexer: context [
    #import ["libRedRT.dylib" stdcall [
        scan: "red/lexer/scan" [[red-internal] dst [cell!] src [pointer! [byte!]] size [integer!] one? [logic!] scan? [logic!] load? [logic!] wrap? [logic!] len [pointer! [integer!]] fun [red-function!] ser [red-series!] out [red-block!] return: [integer!]]
        scan-alt: "red/lexer/scan-alt" [[red-internal] dst [cell!] str [red-string!] size [integer!] one? [logic!] scan? [logic!] load? [logic!] wrap? [logic!] len [pointer! [integer!]] fun [red-function!] out [red-block!] return: [integer!]]
    ]]
]
none: context [
    #import ["libRedRT.dylib" stdcall [
        push-last: "red/none/push-last" [[red-internal] return: [cell!]]
        push: "red/none/push" [[red-internal] return: [cell!]]
    ]]
]
logic: context [
    #import ["libRedRT.dylib" stdcall [
        false?: "red/logic/false?" [[red-internal] return: [logic!]]
        true?: "red/logic/true?" [[red-internal] return: [logic!]]
        push: "red/logic/push" [[red-internal] value [logic!] return: [red-logic!]]
        get: "red/logic/get" [[red-internal] value [cell!] return: [logic!]]
        box: "red/logic/box" [[red-internal] value [logic!] return: [red-logic!]]
        make-in: "red/logic/make-in" [[red-internal] parent [red-block!] value [logic!] return: [red-logic!]]
    ]]
]
refinement: context [
    #import ["libRedRT.dylib" stdcall [
        push-local: "red/refinement/push-local" [[red-internal] node [integer!] index [integer!] return: [red-refinement!]]
        push: "red/refinement/push" [[red-internal] w [red-word!]]
    ]]
]
lit-word: context [
    #import ["libRedRT.dylib" stdcall [
        push-local: "red/lit-word/push-local" [[red-internal] node [integer!] index [integer!] return: [red-word!]]
        push: "red/lit-word/push" [[red-internal] w [red-word!] return: [red-word!]]
    ]]
]
binary: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/binary/push" [[red-internal] bin [red-binary!]]
        rs-head: "red/binary/rs-head" [[red-internal] bin [red-binary!] return: [pointer! [byte!]]]
        rs-tail: "red/binary/rs-tail" [[red-internal] bin [red-binary!] return: [pointer! [byte!]]]
        rs-length?: "red/binary/rs-length?" [[red-internal] bin [red-binary!] return: [integer!]]
    ]]
]
block: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/block/push" [[red-internal] blk [red-block!]]
        push-only*: "red/block/push-only*" [[red-internal] size [integer!] return: [red-block!]]
        insert-thru: "red/block/insert-thru" [[red-internal]]
        append-thru: "red/block/append-thru" [[red-internal]]
        rs-head: "red/block/rs-head" [[red-internal] blk [red-block!] return: [cell!]]
        rs-next: "red/block/rs-next" [[red-internal] blk [red-block!] return: [logic!]]
        rs-tail?: "red/block/rs-tail?" [[red-internal] blk [red-block!] return: [logic!]]
        rs-length?: "red/block/rs-length?" [[red-internal] blk [red-block!] return: [integer!]]
        rs-abs-at: "red/block/rs-abs-at" [[red-internal] blk [red-block!] pos [integer!] return: [cell!]]
        rs-append: "red/block/rs-append" [[red-internal] blk [red-block!] value [cell!] return: [cell!]]
        rs-tail: "red/block/rs-tail" [[red-internal] blk [red-block!] return: [cell!]]
        rs-clear: "red/block/rs-clear" [[red-internal] blk [red-block!]]
        make-at: "red/block/make-at" [[red-internal] blk [red-block!] size [integer!] return: [red-block!]]
        select-word: "red/block/select-word" [[red-internal] blk [red-block!] word [red-word!] case? [logic!] return: [cell!]]
        find: "red/block/find" [[red-internal] blk [red-block!] value [cell!] part [cell!] only? [logic!] case? [logic!] same? [logic!] any? [logic!] with-arg [red-string!] skip [red-integer!] last? [logic!] reverse? [logic!] tail? [logic!] match? [logic!] return: [cell!]]
    ]]
]
char: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/char/push" [[red-internal] value [integer!] return: [red-char!]]
    ]]
]
datatype: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/datatype/push" [[red-internal] type [integer!] return: [red-datatype!]]
        register: "red/datatype/register" [[variadic red-internal] count [integer!] list [pointer! [uint64!]]]
    ]]
]
date: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/date/push" [[red-internal] date [integer!] time [float!] return: [red-date!]]
    ]]
]
email: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/email/push" [[red-internal] email [red-email!]]
    ]]
]
file: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/file/push" [[red-internal] file [red-file!]]
    ]]
]
float: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/float/push" [[red-internal] value [float!] return: [red-float!]]
        push64: "red/float/push64" [[red-internal] high [integer!] low [integer!] return: [red-float!]]
        get: "red/float/get" [[red-internal] value [cell!] return: [float!]]
        box: "red/float/box" [[red-internal] value [float!] return: [red-float!]]
    ]]
]
_function: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/_function/push" [[red-internal] spec [red-block!] body [red-block!] ctx [integer!] code [integer!] obj-ctx [integer!] flags [integer!] return: [integer!]]
        init-locals: "red/_function/init-locals" [[red-internal] nb [integer!]]
    ]]
]
get-path: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/get-path/push" [[red-internal] p [red-block!]]
    ]]
]
get-word: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/get-word/push" [[red-internal] w [red-word!] return: [red-word!]]
        get: "red/get-word/get" [[red-internal] word [red-word!] return: [cell!]]
        push-local: "red/get-word/push-local" [[red-internal] node [integer!] index [integer!] return: [red-word!]]
    ]]
]
integer: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/integer/push" [[red-internal] value [integer!] return: [red-integer!]]
        get-any*: "red/integer/get-any*" [[red-internal] return: [integer!]]
        get*: "red/integer/get*" [[red-internal] return: [integer!]]
        get: "red/integer/get" [[red-internal] value [cell!] return: [integer!]]
        make-at: "red/integer/make-at" [[red-internal] slot [cell!] value [integer!] return: [red-integer!]]
        form-signed: "red/integer/form-signed" [[red-internal] i [integer!] return: [c-string!]]
        box: "red/integer/box" [[red-internal] value [integer!] return: [red-integer!]]
        make-in: "red/integer/make-in" [[red-internal] parent [red-block!] value [integer!] return: [red-integer!]]
    ]]
]
issue: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/issue/push" [[red-internal] w [red-word!]]
    ]]
]
lit-path: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/lit-path/push" [[red-internal] p [red-block!]]
    ]]
]
map: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/map/push" [[red-internal] map [red-hash!]]
    ]]
]
money: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/money/push" [[red-internal] sign [logic!] currency [integer!] amount [c-string!] return: [red-money!]]
    ]]
]
object: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/object/push" [[red-internal] ctx [integer!] evt [integer!] class [integer!] idx-s [integer!] loc-s [integer!] idx-d [integer!] loc-d [integer!] return: [red-object!]]
        clone-series: "red/object/clone-series" [[red-internal] src [integer!] dst [integer!] copy? [logic!]]
        transfer: "red/object/transfer" [[red-internal] src [integer!] dst [integer!]]
        init-push: "red/object/init-push" [[red-internal] node [integer!] class [integer!] return: [red-object!]]
        init-events: "red/object/init-events" [[red-internal] ctx [integer!] idx-s [integer!] loc-s [integer!] idx-d [integer!] loc-d [integer!] return: [integer!]]
        loc-fire-on-set*: "red/object/loc-fire-on-set*" [[red-internal] parent [cell!] field [red-word!]]
        loc-ctx-fire-on-set*: "red/object/loc-ctx-fire-on-set*" [[red-internal] parent-ctx [integer!] field [red-word!]]
        fire-on-set*: "red/object/fire-on-set*" [[red-internal] parent [red-word!] field [red-word!]]
        get-values: "red/object/get-values" [[red-internal] obj [red-object!] return: [cell!]]
        unchanged?: "red/object/unchanged?" [[red-internal] word [red-word!] id [integer!] return: [logic!]]
        unchanged2?: "red/object/unchanged2?" [[red-internal] node [integer!] index [integer!] id [integer!] return: [logic!]]
        get-word: "red/object/get-word" [[red-internal] obj [integer!] index [integer!] return: [cell!]]
        rs-find: "red/object/rs-find" [[red-internal] obj [red-object!] value [cell!] return: [integer!]]
        set-compiled-method: "red/object/set-compiled-method" [[red-internal] ctx-handle [integer!] index [integer!] code [integer!]]
    ]]
]
pair: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/pair/push" [[red-internal] x [integer!] y [integer!] return: [red-pair!]]
    ]]
]
paren: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/paren/push" [[red-internal] paren [red-paren!]]
    ]]
]
path: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/path/push" [[red-internal] p [red-path!]]
    ]]
]
percent: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/percent/push" [[red-internal] value [float!] return: [red-float!]]
        push64: "red/percent/push64" [[red-internal] high [integer!] low [integer!] return: [red-float!]]
    ]]
]
point2D: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/point2D/push" [[red-internal] x [float32!] y [float32!] return: [red-point2D!]]
    ]]
]
point3D: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/point3D/push" [[red-internal] x [float32!] y [float32!] z [float32!] return: [red-point3D!]]
    ]]
]
ref: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/ref/push" [[red-internal] ref [red-ref!]]
    ]]
]
routine: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/routine/push" [[red-internal] spec [red-block!] body [red-block!] code [integer!] ret-type [integer!] extern? [logic!] return: [red-routine!]]
    ]]
]
set-path: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/set-path/push" [[red-internal] p [red-block!]]
    ]]
]
set-word: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/set-word/push" [[red-internal] w [red-word!] return: [red-word!]]
        push-local: "red/set-word/push-local" [[red-internal] node [integer!] index [integer!] return: [red-word!]]
    ]]
]
string: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/string/push" [[red-internal] str [red-string!] return: [red-string!]]
        rs-head: "red/string/rs-head" [[red-internal] str [red-string!] return: [pointer! [byte!]]]
        rs-tail?: "red/string/rs-tail?" [[red-internal] str [red-string!] return: [logic!]]
        equal?: "red/string/equal?" [[red-internal] str1 [red-string!] str2 [red-string!] op [integer!] match? [logic!] return: [integer!]]
        rs-make-at: "red/string/rs-make-at" [[red-internal] slot [cell!] size [integer!] return: [red-string!]]
        get-char: "red/string/get-char" [[red-internal] p [pointer! [byte!]] unit [integer!] return: [integer!]]
        rs-reset: "red/string/rs-reset" [[red-internal] str [red-string!]]
        concatenate: "red/string/concatenate" [[red-internal] str1 [red-string!] str2 [red-string!] part [integer!] offset [integer!] keep? [logic!] insert? [logic!]]
        rs-length?: "red/string/rs-length?" [[red-internal] str [red-string!] return: [integer!]]
        concatenate-literal: "red/string/concatenate-literal" [[red-internal] str [red-string!] p [c-string!] return: [series-buffer!]]
        append-char: "red/string/append-char" [[red-internal] s [series-buffer!] cp [integer!] return: [series-buffer!]]
        insert-char: "red/string/insert-char" [[red-internal] s [series-buffer!] offset [integer!] cp [integer!] return: [series-buffer!]]
        rs-abs-length?: "red/string/rs-abs-length?" [[red-internal] str [red-string!] return: [integer!]]
        remove-char: "red/string/remove-char" [[red-internal] str [red-string!] offset [integer!] return: [red-string!]]
        poke-char: "red/string/poke-char" [[red-internal] s [series-buffer!] p [pointer! [byte!]] cp [integer!] return: [series-buffer!]]
        remove-part: "red/string/remove-part" [[red-internal] str [red-string!] offset [integer!] part [integer!] return: [red-string!]]
        to-hex: "red/string/to-hex" [[red-internal] value [integer!] char? [logic!] return: [c-string!]]
        make-at: "red/string/make-at" [[red-internal] slot [cell!] size [integer!] unit [integer!] return: [red-string!]]
        load: "red/string/load" [[red-internal] src [c-string!] size [integer!] encoding [integer!] return: [red-string!]]
        load-at: "red/string/load-at" [[red-internal] src [c-string!] size [integer!] slot [cell!] encoding [integer!] return: [red-string!]]
    ]]
]
tag: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/tag/push" [[red-internal] tag [red-tag!]]
    ]]
]
time: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/time/push" [[red-internal] time [float!] return: [red-time!]]
    ]]
]
tuple: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/tuple/push" [[red-internal] size [integer!] arr1 [integer!] arr2 [integer!] arr3 [integer!] return: [red-tuple!]]
    ]]
]
typeset: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/typeset/push" [[red-internal] sets [red-typeset!]]
    ]]
]
unset: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/unset/push" [[red-internal] return: [red-unset!]]
    ]]
]
url: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/url/push" [[red-internal] url [red-url!]]
    ]]
]
vector: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/vector/push" [[red-internal] vec [red-vector!]]
        rs-head: "red/vector/rs-head" [[red-internal] vec [red-vector!] return: [pointer! [byte!]]]
        rs-tail: "red/vector/rs-tail" [[red-internal] vec [red-vector!] return: [pointer! [byte!]]]
        rs-tail?: "red/vector/rs-tail?" [[red-internal] vec [red-vector!] return: [logic!]]
        rs-length?: "red/vector/rs-length?" [[red-internal] vec [red-vector!] return: [integer!]]
        rs-skip: "red/vector/rs-skip" [[red-internal] vec [red-vector!] len [integer!] return: [logic!]]
        rs-next: "red/vector/rs-next" [[red-internal] vec [red-vector!] return: [logic!]]
        rs-clear: "red/vector/rs-clear" [[red-internal] vec [red-vector!]]
        rs-append: "red/vector/rs-append" [[red-internal] vec [red-vector!] value [cell!] return: [cell!]]
        rs-append-int: "red/vector/rs-append-int" [[red-internal] vec [red-vector!] n [integer!]]
        rs-overwrite: "red/vector/rs-overwrite" [[red-internal] vec [red-vector!] offset [integer!] value [cell!] return: [series-buffer!]]
        rs-insert: "red/vector/rs-insert" [[red-internal] vec [red-vector!] offset [integer!] value [cell!] return: [series-buffer!]]
        get-value: "red/vector/get-value" [[red-internal] p [pointer! [byte!]] unit [integer!] type [integer!] return: [cell!]]
        get-value-int: "red/vector/get-value-int" [[red-internal] p [pointer! [integer!]] unit [integer!] return: [integer!]]
        get-value-float: "red/vector/get-value-float" [[red-internal] p [pointer! [byte!]] unit [integer!] return: [float!]]
        set-value: "red/vector/set-value" [[red-internal] p [pointer! [byte!]] value [cell!] unit [integer!]]
    ]]
]
word: context [
    #import ["libRedRT.dylib" stdcall [
        push: "red/word/push" [[red-internal] word [red-word!] return: [red-word!]]
        get: "red/word/get" [[red-internal] word [red-word!] return: [cell!]]
        get-local: "red/word/get-local" [[red-internal] node [integer!] index [integer!] return: [cell!]]
        get-any: "red/word/get-any" [[red-internal] word [red-word!] return: [cell!]]
        get-in: "red/word/get-in" [[red-internal] node [integer!] index [integer!] return: [cell!]]
        set-in: "red/word/set-in" [[red-internal] node [integer!] index [integer!] return: [cell!]]
        set-in-ctx: "red/word/set-in-ctx" [[red-internal] node [integer!] index [integer!]]
        set: "red/word/set" [[red-internal]]
        replace: "red/word/replace" [[red-internal] node [integer!] index [integer!]]
        from: "red/word/from" [[red-internal] node [integer!] index [integer!] return: [red-word!]]
        load: "red/word/load" [[red-internal] str [c-string!] return: [red-word!]]
        push-local: "red/word/push-local" [[red-internal] node [integer!] index [integer!] return: [red-word!]]
        duplicate: "red/word/duplicate" [[red-internal] w [red-word!] return: [red-word!]]
        push*: "red/word/push*" [[red-internal] id [integer!] return: [red-word!]]
        make-at: "red/word/make-at" [[red-internal] id [integer!] pos [cell!] return: [red-word!]]
        push-in: "red/word/push-in" [[red-internal] id [integer!] blk [red-block!] return: [red-word!]]
    ]]
]
_context: context [
    #import ["libRedRT.dylib" stdcall [
        get: "red/_context/get" [[red-internal] word [red-word!] return: [cell!]]
        clone-words: "red/_context/clone-words" [[red-internal] slot [red-block!] type [context-type!] return: [integer!]]
        set-integer: "red/_context/set-integer" [[red-internal] word [red-word!] value [integer!] return: [integer!]]
        set: "red/_context/set" [[red-internal] word [red-word!] value [cell!] return: [cell!]]
    ]]
]
handle: context [
    #import ["libRedRT.dylib" stdcall [
        box: "red/handle/box" [[red-internal] value [integer!] type [integer!] return: [red-handle!]]
        make-in: "red/handle/make-in" [[red-internal] parent [red-block!] value [integer!] type [integer!] return: [red-handle!]]
    ]]
]
_series: context [
    #import ["libRedRT.dylib" stdcall [
        copy: "red/_series/copy" [[red-internal] ser [red-series!] new [red-series!] part-arg [cell!] deep? [logic!] types [cell!] return: [red-series!]]
        remove: "red/_series/remove" [[red-internal] ser [red-series!] part-arg [cell!] key-arg [cell!] return: [red-series!]]
    ]]
]
symbol: context [
    #import ["libRedRT.dylib" stdcall [
        make: "red/symbol/make" [[red-internal] s [c-string!] return: [integer!]]
        resolve: "red/symbol/resolve" [[red-internal] id [integer!] return: [integer!]]
    ]]
]
unicode: context [
    #import ["libRedRT.dylib" stdcall [
        load-utf8: "red/unicode/load-utf8" [[red-internal] src [c-string!] size [integer!] return: [ptr-ptr!]]
        decode-utf8-char: "red/unicode/decode-utf8-char" [[red-internal] src [c-string!] cnt [pointer! [integer!]] return: [integer!]]
        convert-u16: "red/unicode/convert-u16" [[red-internal] src [c-string!] dst [c-string!] return: [c-string!]]
        to-utf8: "red/unicode/to-utf8" [[red-internal] str [red-string!] len [pointer! [integer!]] return: [c-string!]]
        load-utf8-buffer: "red/unicode/load-utf8-buffer" [[red-internal] src [c-string!] size [integer!] dst [series-buffer!] remain [pointer! [integer!]] convert? [logic!] return: [ptr-ptr!]]
        load-utf8-stream: "red/unicode/load-utf8-stream" [[red-internal] src [c-string!] size [integer!] output [red-string!] remain [pointer! [integer!]] return: [ptr-ptr!]]
    ]]
]
natives: context [
    #import ["libRedRT.dylib" stdcall [
        remove-each-init: "red/natives/remove-each-init" [[red-internal]]
        remove-each-next: "red/natives/remove-each-next" [[red-internal] size [integer!]]
        foreach-next-block: "red/natives/foreach-next-block" [[red-internal] size [integer!] return: [logic!]]
        foreach-next: "red/natives/foreach-next" [[red-internal] return: [logic!]]
        forall-next?: "red/natives/forall-next?" [[red-internal] inc? [logic!] return: [logic!]]
        forall-end: "red/natives/forall-end" [[red-internal]]
        forall-end-adjust: "red/natives/forall-end-adjust" [[red-internal]]
        coerce-counter*: "red/natives/coerce-counter*" [[red-internal]]
        inc-counter: "red/natives/inc-counter" [[red-internal] w [red-word!]]
        if*: "red/natives/if*" [[red-internal] check? [logic!]]
        unless*: "red/natives/unless*" [[red-internal] check? [logic!]]
        either*: "red/natives/either*" [[red-internal] check? [logic!]]
        any*: "red/natives/any*" [[red-internal] check? [logic!]]
        all*: "red/natives/all*" [[red-internal] check? [logic!]]
        while*: "red/natives/while*" [[red-internal] check? [logic!]]
        until*: "red/natives/until*" [[red-internal] check? [logic!]]
        loop*: "red/natives/loop*" [[red-internal] check? [logic!]]
        repeat*: "red/natives/repeat*" [[red-internal] check? [logic!]]
        forever*: "red/natives/forever*" [[red-internal] check? [logic!]]
        foreach*: "red/natives/foreach*" [[red-internal] check? [logic!]]
        forall*: "red/natives/forall*" [[red-internal] check? [logic!]]
        func*: "red/natives/func*" [[red-internal] check? [logic!]]
        function*: "red/natives/function*" [[red-internal] check? [logic!]]
        does*: "red/natives/does*" [[red-internal] check? [logic!]]
        has*: "red/natives/has*" [[red-internal] check? [logic!]]
        switch*: "red/natives/switch*" [[red-internal] check? [logic!] default? [integer!]]
        case*: "red/natives/case*" [[red-internal] check? [logic!] all? [integer!]]
        do*: "red/natives/do*" [[red-internal] check? [logic!] expand? [integer!] args [integer!] next [integer!] trace [integer!] return: [integer!]]
        get*: "red/natives/get*" [[red-internal] check? [logic!] any? [integer!] case? [integer!]]
        set*: "red/natives/set*" [[red-internal] check? [logic!] _any? [integer!] case? [integer!] _only? [integer!] _some? [integer!]]
        print*: "red/natives/print*" [[red-internal] check? [logic!]]
        prin*: "red/natives/prin*" [[red-internal] check? [logic!]]
        equal?*: "red/natives/equal?*" [[red-internal] check? [logic!] return: [red-logic!]]
        not-equal?*: "red/natives/not-equal?*" [[red-internal] check? [logic!] return: [red-logic!]]
        strict-equal?*: "red/natives/strict-equal?*" [[red-internal] check? [logic!] return: [red-logic!]]
        lesser?*: "red/natives/lesser?*" [[red-internal] check? [logic!] return: [red-logic!]]
        greater?*: "red/natives/greater?*" [[red-internal] check? [logic!] return: [red-logic!]]
        lesser-or-equal?*: "red/natives/lesser-or-equal?*" [[red-internal] check? [logic!] return: [red-logic!]]
        greater-or-equal?*: "red/natives/greater-or-equal?*" [[red-internal] check? [logic!] return: [red-logic!]]
        same?*: "red/natives/same?*" [[red-internal] check? [logic!] return: [red-logic!]]
        not*: "red/natives/not*" [[red-internal] check? [logic!]]
        type?*: "red/natives/type?*" [[red-internal] check? [logic!] word? [integer!] return: [cell!]]
        reduce*: "red/natives/reduce*" [[red-internal] check? [logic!] into [integer!]]
        compose*: "red/natives/compose*" [[red-internal] check? [logic!] deep [integer!] only [integer!] into [integer!]]
        stats*: "red/natives/stats*" [[red-internal] check? [logic!] show [integer!] info [integer!]]
        bind*: "red/natives/bind*" [[red-internal] check? [logic!] copy [integer!]]
        in*: "red/natives/in*" [[red-internal] check? [logic!]]
        parse*: "red/natives/parse*" [[red-internal] check? [logic!] case? [integer!] part [integer!] trace [integer!] return: [integer!]]
        union*: "red/natives/union*" [[red-internal] check? [logic!] cased [integer!] skip [integer!]]
        intersect*: "red/natives/intersect*" [[red-internal] check? [logic!] cased [integer!] skip [integer!]]
        unique*: "red/natives/unique*" [[red-internal] check? [logic!] cased [integer!] skip [integer!]]
        difference*: "red/natives/difference*" [[red-internal] check? [logic!] cased [integer!] skip [integer!]]
        exclude*: "red/natives/exclude*" [[red-internal] check? [logic!] cased [integer!] skip [integer!]]
        complement?*: "red/natives/complement?*" [[red-internal] check? [logic!] return: [red-logic!]]
        dehex*: "red/natives/dehex*" [[red-internal] check? [logic!] return: [red-string!]]
        enhex*: "red/natives/enhex*" [[red-internal] check? [logic!] return: [red-string!]]
        negative?*: "red/natives/negative?*" [[red-internal] check? [logic!] return: [red-logic!]]
        positive?*: "red/natives/positive?*" [[red-internal] check? [logic!] return: [red-logic!]]
        max*: "red/natives/max*" [[red-internal] check? [logic!]]
        min*: "red/natives/min*" [[red-internal] check? [logic!]]
        shift*: "red/natives/shift*" [[red-internal] check? [logic!] left [integer!] logical [integer!]]
        to-hex*: "red/natives/to-hex*" [[red-internal] check? [logic!] size [integer!]]
        sine*: "red/natives/sine*" [[red-internal] check? [logic!] radians [integer!]]
        cosine*: "red/natives/cosine*" [[red-internal] check? [logic!] radians [integer!]]
        tangent*: "red/natives/tangent*" [[red-internal] check? [logic!] radians [integer!]]
        arcsine*: "red/natives/arcsine*" [[red-internal] check? [logic!] radians [integer!]]
        arccosine*: "red/natives/arccosine*" [[red-internal] check? [logic!] radians [integer!]]
        arctangent*: "red/natives/arctangent*" [[red-internal] check? [logic!] radians [integer!]]
        arctangent2*: "red/natives/arctangent2*" [[red-internal] check? [logic!] radians [integer!]]
        NaN?*: "red/natives/NaN?*" [[red-internal] check? [logic!] return: [red-logic!]]
        log-2*: "red/natives/log-2*" [[red-internal] check? [logic!]]
        log-10*: "red/natives/log-10*" [[red-internal] check? [logic!]]
        log-e*: "red/natives/log-e*" [[red-internal] check? [logic!]]
        exp*: "red/natives/exp*" [[red-internal] check? [logic!]]
        square-root*: "red/natives/square-root*" [[red-internal] check? [logic!]]
        construct*: "red/natives/construct*" [[red-internal] check? [logic!] _with [integer!] only [integer!]]
        value?*: "red/natives/value?*" [[red-internal] check? [logic!]]
        try*: "red/natives/try*" [[red-internal] check? [logic!] _all [integer!] keep [integer!] return: [integer!]]
        uppercase*: "red/natives/uppercase*" [[red-internal] check? [logic!] part [integer!]]
        lowercase*: "red/natives/lowercase*" [[red-internal] check? [logic!] part [integer!]]
        as-pair*: "red/natives/as-pair*" [[red-internal] check? [logic!]]
        break*: "red/natives/break*" [[red-internal] check? [logic!] returned [integer!]]
        continue*: "red/natives/continue*" [[red-internal] check? [logic!]]
        exit*: "red/natives/exit*" [[red-internal] check? [logic!]]
        return*: "red/natives/return*" [[red-internal] check? [logic!]]
        throw*: "red/natives/throw*" [[red-internal] check? [logic!] name [integer!]]
        catch*: "red/natives/catch*" [[red-internal] check? [logic!] name [integer!]]
        extend*: "red/natives/extend*" [[red-internal] check? [logic!] case? [integer!]]
        debase*: "red/natives/debase*" [[red-internal] check? [logic!] base-arg [integer!]]
        to-local-file*: "red/natives/to-local-file*" [[red-internal] check? [logic!] full? [integer!]]
        wait*: "red/natives/wait*" [[red-internal] check? [logic!] all? [integer!]]
        checksum*: "red/natives/checksum*" [[red-internal] check? [logic!] _with [integer!]]
        unset*: "red/natives/unset*" [[red-internal] check? [logic!]]
        new-line*: "red/natives/new-line*" [[red-internal] check? [logic!] _all [integer!] skip [integer!]]
        new-line?*: "red/natives/new-line?*" [[red-internal] check? [logic!]]
        enbase*: "red/natives/enbase*" [[red-internal] check? [logic!] base-arg [integer!]]
        handle-thrown-error: "red/natives/handle-thrown-error" [[red-internal] keep? [logic!]]
        now*: "red/natives/now*" [[red-internal] check? [logic!] year [integer!] month [integer!] day [integer!] time [integer!] zone [integer!] _date [integer!] weekday [integer!] yearday [integer!] precise [integer!] utc [integer!]]
        get-env*: "red/natives/get-env*" [[red-internal] check? [logic!]]
        set-env*: "red/natives/set-env*" [[red-internal] check? [logic!]]
        list-env*: "red/natives/list-env*" [[red-internal] check? [logic!]]
        sign?*: "red/natives/sign?*" [[red-internal] check? [logic!] return: [red-integer!]]
        as*: "red/natives/as*" [[red-internal] check? [logic!]]
        call*: "red/natives/call*" [[red-internal] check? [logic!] wait [integer!] show [integer!] console [integer!] shell [integer!] input [integer!] output [integer!] error [integer!] return: [red-integer!]]
        zero?*: "red/natives/zero?*" [[red-internal] check? [logic!] return: [red-logic!]]
        size?*: "red/natives/size?*" [[red-internal] check? [logic!]]
        browse*: "red/natives/browse*" [[red-internal] check? [logic!]]
        context?*: "red/natives/context?*" [[red-internal] check? [logic!]]
        compress*: "red/natives/compress*" [[red-internal] check? [logic!]]
        decompress*: "red/natives/decompress*" [[red-internal] check? [logic!] size [integer!]]
        recycle*: "red/natives/recycle*" [[red-internal] check? [logic!] on? [integer!] off? [integer!]]
        transcode*: "red/natives/transcode*" [[red-internal] check? [logic!] next [integer!] one [integer!] prescan [integer!] scan [integer!] part [integer!] into [integer!] trace [integer!]]
        as-money*: "red/natives/as-money*" [[red-internal] check? [logic!]]
        apply*: "red/natives/apply*" [[red-internal] check? [logic!] _all [integer!] safer [integer!]]
        as-point2D*: "red/natives/as-point2D*" [[red-internal] check? [logic!]]
        as-point3D*: "red/natives/as-point3D*" [[red-internal] check? [logic!]]
        buffer-blk: "red/natives/buffer-blk" [red-block!]
    ]]
]
actions: context [
    #import ["libRedRT.dylib" stdcall [
        make*: "red/actions/make*" [[red-internal] return: [cell!]]
        random*: "red/actions/random*" [[red-internal] seed [integer!] secure [integer!] only [integer!] return: [cell!]]
        reflect*: "red/actions/reflect*" [[red-internal] return: [red-block!]]
        to*: "red/actions/to*" [[red-internal] return: [cell!]]
        form*: "red/actions/form*" [[red-internal] part [integer!]]
        mold*: "red/actions/mold*" [[red-internal] only [integer!] _all [integer!] flat [integer!] part [integer!]]
        eval-path*: "red/actions/eval-path*" [[red-internal] set? [logic!] return: [cell!]]
        compare: "red/actions/compare" [[red-internal] value1 [cell!] value2 [cell!] op [comparison-op!] return: [logic!]]
        op2*: "red/actions/op2*" [[red-internal] op [integer!] sym [red-word!] left [cell!] right [cell!] return: [cell!]]
        op2i*: "red/actions/op2i*" [[red-internal] op [integer!] sym [red-word!] left [cell!] i2 [integer!] return: [cell!]]
        cmp2*: "red/actions/cmp2*" [[red-internal] op [integer!] sym [red-word!] left [cell!] right [cell!] return: [red-logic!]]
        cmp2i*: "red/actions/cmp2i*" [[red-internal] op [integer!] sym [red-word!] left [cell!] i2 [integer!] return: [red-logic!]]
        cmp2b*: "red/actions/cmp2b*" [[red-internal] op [integer!] sym [red-word!] left [cell!] right [cell!] not? [logic!] return: [logic!]]
        cmp2ib*: "red/actions/cmp2ib*" [[red-internal] op [integer!] sym [red-word!] left [cell!] i2 [integer!] not? [logic!] return: [logic!]]
        absolute*: "red/actions/absolute*" [[red-internal] return: [cell!]]
        add*: "red/actions/add*" [[red-internal] return: [cell!]]
        divide*: "red/actions/divide*" [[red-internal] return: [cell!]]
        multiply*: "red/actions/multiply*" [[red-internal] return: [cell!]]
        negate*: "red/actions/negate*" [[red-internal] return: [cell!]]
        power*: "red/actions/power*" [[red-internal] return: [cell!]]
        remainder*: "red/actions/remainder*" [[red-internal] return: [cell!]]
        round*: "red/actions/round*" [[red-internal] _to [integer!] even [integer!] down [integer!] half-down [integer!] floor [integer!] ceil [integer!] half-ceil [integer!]]
        subtract*: "red/actions/subtract*" [[red-internal] return: [cell!]]
        even?*: "red/actions/even?*" [[red-internal] return: [red-logic!]]
        odd?*: "red/actions/odd?*" [[red-internal] return: [red-logic!]]
        and~*: "red/actions/and~*" [[red-internal] return: [cell!]]
        complement*: "red/actions/complement*" [[red-internal]]
        or~*: "red/actions/or~*" [[red-internal] return: [cell!]]
        xor~*: "red/actions/xor~*" [[red-internal] return: [cell!]]
        append*: "red/actions/append*" [[red-internal] part [integer!] only [integer!] dup [integer!]]
        at*: "red/actions/at*" [[red-internal] return: [cell!]]
        back*: "red/actions/back*" [[red-internal] return: [cell!]]
        change*: "red/actions/change*" [[red-internal] part [integer!] only [integer!] dup [integer!] return: [red-series!]]
        clear*: "red/actions/clear*" [[red-internal] return: [cell!]]
        copy*: "red/actions/copy*" [[red-internal] part [integer!] deep [integer!] types [integer!] return: [cell!]]
        find*: "red/actions/find*" [[red-internal] part [integer!] only [integer!] case-arg [integer!] same-arg [integer!] any-arg [integer!] with-arg [integer!] skip [integer!] last [integer!] reverse [integer!] tail [integer!] match [integer!]]
        head*: "red/actions/head*" [[red-internal] return: [cell!]]
        head?*: "red/actions/head?*" [[red-internal] return: [cell!]]
        index?*: "red/actions/index?*" [[red-internal] return: [cell!]]
        insert*: "red/actions/insert*" [[red-internal] part [integer!] only [integer!] dup [integer!]]
        move*: "red/actions/move*" [[red-internal] part [integer!] return: [cell!]]
        length?*: "red/actions/length?*" [[red-internal] return: [red-integer!]]
        next*: "red/actions/next*" [[red-internal] return: [cell!]]
        pick*: "red/actions/pick*" [[red-internal] return: [cell!]]
        poke*: "red/actions/poke*" [[red-internal] return: [cell!]]
        put*: "red/actions/put*" [[red-internal] case? [integer!]]
        remove*: "red/actions/remove*" [[red-internal] part [integer!] key [integer!]]
        reverse*: "red/actions/reverse*" [[red-internal] part [integer!] skip [integer!]]
        select*: "red/actions/select*" [[red-internal] part [integer!] only [integer!] case-arg [integer!] same-arg [integer!] any-arg [integer!] with-arg [integer!] skip [integer!] last [integer!] reverse [integer!]]
        sort*: "red/actions/sort*" [[red-internal] case-arg [integer!] skip-arg [integer!] compare [integer!] part [integer!] all-arg [integer!] reverse [integer!] stable [integer!]]
        skip*: "red/actions/skip*" [[red-internal] return: [cell!]]
        swap*: "red/actions/swap*" [[red-internal] return: [red-series!]]
        tail*: "red/actions/tail*" [[red-internal] return: [cell!]]
        tail?*: "red/actions/tail?*" [[red-internal] return: [cell!]]
        take*: "red/actions/take*" [[red-internal] part [integer!] deep [integer!] last [integer!] return: [cell!]]
        trim*: "red/actions/trim*" [[red-internal] head [integer!] tail [integer!] auto [integer!] lines [integer!] _all [integer!] with-arg [integer!] return: [red-series!]]
        create*: "red/actions/create*" [[red-internal] return: [cell!]]
        close*: "red/actions/close*" [[red-internal] return: [cell!]]
        delete*: "red/actions/delete*" [[red-internal] return: [cell!]]
        modify*: "red/actions/modify*" [[red-internal] case? [integer!] return: [cell!]]
        open*: "red/actions/open*" [[red-internal] new [integer!] read [integer!] write [integer!] seek [integer!] allow [integer!]]
        query*: "red/actions/query*" [[red-internal]]
        read*: "red/actions/read*" [[red-internal] part [integer!] seek [integer!] binary? [integer!] lines? [integer!] info? [integer!] as-arg [integer!] return: [cell!]]
        rename*: "red/actions/rename*" [[red-internal] return: [cell!]]
        update*: "red/actions/update*" [[red-internal] return: [cell!]]
        write*: "red/actions/write*" [[red-internal] binary? [integer!] lines? [integer!] info? [integer!] append? [integer!] part [integer!] seek [integer!] allow [integer!] as-arg [integer!] return: [cell!]]
    ]]
]
ownership: context [
    #import ["libRedRT.dylib" stdcall [
        bind: "red/ownership/bind" [[red-internal] container [cell!] owner [red-object!] word [red-word!]]
        check: "red/ownership/check" [[red-internal] value [cell!] action [red-word!] new [cell!] index [integer!] part [integer!] return: [logic!]]
    ]]
]
image: context [
    #import ["libRedRT.dylib" stdcall [
        init-image: "red/image/init-image" [[red-internal] img [red-image!] handle [ptr-ptr!] return: [red-image!]]
        push: "red/image/push" [[red-internal] img [red-image!]]
        acquire-buffer: "red/image/acquire-buffer" [[red-internal] img [red-image!] bitmap [ptr-ptr!] return: [pointer! [integer!]]]
        release-buffer: "red/image/release-buffer" [[red-internal] img [red-image!] bitmap [pointer! [integer!]] modified? [logic!]]
    ]]
]
OS-image: context [
    #import ["libRedRT.dylib" stdcall [
        lock-bitmap: "red/OS-image/lock-bitmap" [[red-internal] img [red-image!] write? [logic!] return: [pointer! [integer!]]]
        get-data: "red/OS-image/get-data" [[red-internal] handle [pointer! [integer!]] stride [pointer! [integer!]] return: [pointer! [integer!]]]
        unlock-bitmap: "red/OS-image/unlock-bitmap" [[red-internal] img [red-image!] data [pointer! [integer!]]]
    ]]
]
gui: context [
    #import ["libRedRT.dylib" stdcall [
        OS-alert: "gui/OS-alert" [[red-internal] caption [c-string!] msg [c-string!]]
    ]]
] collector: context [
    #import ["libRedRT.dylib" stdcall [
        active?: "red/collector/active?" [logic!]
    ]]
]
words: context [
    red/boot?: yes
    _body: red/word/load "<body>"
    _anon: red/word/load "<anon>"
    _remove: red/word/load "remove"
    _take: red/word/load "take"
    _clear: red/word/load "clear"
    _insert: red/word/load "insert"
    _poke: red/word/load "poke"
    _put: red/word/load "put"
    _moved: red/word/load "moved"
    _changed: red/word/load "changed"
    _reverse: red/word/load "reverse"
    _lowercase: red/word/load "lowercase"
    _uppercase: red/word/load "uppercase"
    type: red/symbol/make "type"
    face: red/symbol/make "face"
    window: red/symbol/make "window"
    offset: red/symbol/make "offset"
    key: red/symbol/make "key"
    picked: red/symbol/make "picked"
    flags: red/symbol/make "flags"
    away?: red/symbol/make "away?"
    down?: red/symbol/make "down?"
    mid-down?: red/symbol/make "mid-down?"
    alt-down?: red/symbol/make "alt-down?"
    aux-down?: red/symbol/make "aux-down?"
    ctrl?: red/symbol/make "ctrl?"
    shift?: red/symbol/make "shift?"
    red/boot?: no
]]